platform :ios, '8.0'
inhibit_all_warnings!

target "内存管理实例" do
    use_frameworks!
    pod 'SDWebImage', '3.8.2'
    pod 'SDWebImage/WebP'
    pod 'Masonry'
    pod 'TZImagePickerController'
    pod 'ReactiveCocoa', '7.1.0'
    pod 'SnapKit', '4.0.0'
end
